# Generated by Django 6.0.3 on 2026-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_systemprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='prompt',
            field=models.TextField(max_length=10000),
        ),
    ]
