# Generated by Django 5.0.6 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_message_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemprompt',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='template_version',
            field=models.CharField(
                blank=True,
                choices=[
                    ('v1', '基础模板'),
                    ('v2', '增强模板-支持用户消息'),
                    ('v3', '高级模板-支持图片分析'),
                ],
                default='v1',
                max_length=10,
            ),
        ),
    ]