# Generated by Django 6.0.4 on 2026-04-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_fix_image_caption_null'),
        ('web', '0009_systemprompt_template'),
    ]

    operations = [
    ]
