# Generated by Django 6.0.4 on 2026-04-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_merge_20260424_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemprompt',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='systemprompt',
            name='template_version',
        ),
        migrations.AddField(
            model_name='friend',
            name='conversation_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='friend',
            name='summary_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
