# Generated by Django 6.0.4 on 2026-04-25 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_add_conversation_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('preference', '偏好'), ('event', '事件'), ('fact', '事实'), ('emotion', '情感'), ('general', '通用')], default='general', max_length=32)),
                ('importance', models.FloatField(default=0.5)),
                ('weight', models.FloatField(default=0.5)),
                ('access_count', models.IntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='web.friend')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
    ]
