# Generated by Django 6.0.4 on 2026-04-27 11:04

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_memoryitem'),
    ]

    operations = [
        # jsonb → vector(1024) 无法直接转换，需要先转 text 再转 vector
        migrations.RunSQL(
            sql='''
                ALTER TABLE web_memoryitem
                ALTER COLUMN embedding TYPE vector(1024)
                USING embedding::text::vector(1024);
            ''',
            reverse_sql='''
                ALTER TABLE web_memoryitem
                ALTER COLUMN embedding TYPE jsonb
                USING embedding::text::jsonb;
            ''',
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64, fields=['embedding'], m=16,
                name='web_memoryitem_embedding_hnsw',
                opclasses=['vector_cosine_ops'],
            ),
        ),
    ]
