# Generated by Django 6.0.4 on 2026-05-04 03:40

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_memoryitem_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='speaker',
            field=models.CharField(default='longanyang', max_length=50),
        ),
        migrations.AlterField(
            model_name='memoryitem',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
