# Generated by Django 6.0.4 on 2026-05-26 02:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_character_speaker_alter_memoryitem_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('repeat_type', models.CharField(choices=[('none', '不重复'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='none', max_length=20)),
                ('reminder_before', models.IntegerField(default=30)),
                ('source', models.CharField(choices=[('text', '文字'), ('voice', '语音'), ('image', '图片'), ('agent', 'Agent')], default='text', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
